# Generated by Django 4.2.1 on 2023-06-01 22:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Respuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('porcentaje', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionario.preguntas')),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionario.questionario')),
            ],
        ),
        migrations.CreateModel(
            name='UserRespuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.personal')),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionario.questionario')),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionario.respuestas')),
            ],
        ),
        migrations.AddField(
            model_name='preguntas',
            name='questionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionario.questionario'),
        ),
    ]
