# Generated by Django 4.1.3 on 2023-06-04 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altapersonal',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 6, 4, 2, 50, 9, 84348, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='bajapersonal',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 6, 4, 2, 50, 9, 84348, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='paselista',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 6, 4, 2, 50, 9, 85348, tzinfo=datetime.timezone.utc)),
        ),
    ]
