# Generated by Django 4.2.1 on 2023-06-01 22:48

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +999999999. Up to 15 digits allowed.', regex='\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='altapersonal',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 6, 1, 17, 48, 35, 804879)),
        ),
        migrations.AlterField(
            model_name='bajapersonal',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 6, 1, 17, 48, 35, 805970)),
        ),
        migrations.AlterField(
            model_name='paselista',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 6, 1, 17, 48, 35, 806885)),
        ),
    ]
